#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 19 10:05:13 2021

@author: sarahraza
"""

#Homework 7

# Install needed packages
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

filename = r"/Users/sarahraza/Downloads/nosocomial.csv"
nosocomial= pd.read_csv(filename)

#Q3
DIFF = nosocomial.Infected - nosocomial.NotInfected
#print(DIFF)

#Q4

xbar = np.mean(DIFF)
xbar = round(xbar,4)
#print(xbar)

#Q5

sigma = 13.5
n = 52

z_star = stats.norm.ppf(0.95)
z_star = round(z_star,3)

LL = xbar - z_star * sigma/np.sqrt(n)
UL = xbar + z_star * sigma/np.sqrt(n)

LL = round(LL,4)
UL = round(UL,4)

#print(LL)
#print(UL)

#Q6

m_star = z_star * sigma/np.sqrt(n)
m_star = round(m_star,4)
print(m_star)

#Q7

meancompare = 0.1*xbar
meancompare = round(meancompare,4)

#Q8

nfind = ((z_star * sigma)/meancompare)**2
nfind = np.ceil(nfind)
#print(nfind)
